// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrrCiVbm9jRG6N4noWoc5V_hNygrYdGNI',
    appId: '1:1039938398263:web:your-web-app-id',
    messagingSenderId: '1039938398263',
    projectId: 'the-track-fit-57be9',
    authDomain: 'the-track-fit-57be9.firebaseapp.com',
    storageBucket: 'the-track-fit-57be9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrCiVbm9jRG6N4noWoc5V_hNygrYdGNI',
    appId: '1:1039938398263:android:2f877768e63be49e6cf7b2',
    messagingSenderId: '1039938398263',
    projectId: 'the-track-fit-57be9',
    storageBucket: 'the-track-fit-57be9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrrCiVbm9jRG6N4noWoc5V_hNygrYdGNI',
    appId: '1:1039938398263:ios:your-ios-app-id',
    messagingSenderId: '1039938398263',
    projectId: 'the-track-fit-57be9',
    storageBucket: 'the-track-fit-57be9.firebasestorage.app',
    iosBundleId: 'com.example.theTrackFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrrCiVbm9jRG6N4noWoc5V_hNygrYdGNI',
    appId: '1:1039938398263:ios:your-macos-app-id',
    messagingSenderId: '1039938398263',
    projectId: 'the-track-fit-57be9',
    storageBucket: 'the-track-fit-57be9.firebasestorage.app',
    iosBundleId: 'com.example.theTrackFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrrCiVbm9jRG6N4noWoc5V_hNygrYdGNI',
    appId: '1:1039938398263:web:your-windows-app-id',
    messagingSenderId: '1039938398263',
    projectId: 'the-track-fit-57be9',
    authDomain: 'the-track-fit-57be9.firebaseapp.com',
    storageBucket: 'the-track-fit-57be9.firebasestorage.app',
  );
}
